before_script:
    - date
    - uname -a
    - printenv | sort
    
    
frontend:  
    image: gpdowning/node
    script:
        - cd ./frontend
        - npm install
        - npm test
backend_unit:  
    image: gpdowning/python
    script:
        - cd ./backend
        - pip install flask
        - pip install requests
        - pip install flask_cors
        - pip install flask_marshmallow
        - pip install flask_sqlalchemy
        - pip install ConfigParser
        - pip install mysqlclient
        - pip install PyMySQL
        - python tests.py
backend_postman:
    image: gpdowning/node
    script:
        - npm install newman
        - node_modules/.bin/newman run Postman.json